# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
    repository.user:
        class: MyDigitalLife\FakeTwitterBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments: ['MyDigitalLife\FakeTwitterBundle\Entity\User']
    repository.tweet:
        class: MyDigitalLife\FakeTwitterBundle\Repository\TweetRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments: ['MyDigitalLife\FakeTwitterBundle\Entity\Tweet']

    service.search:
        class: MyDigitalLife\FakeTwitterBundle\Service\SearchService
        arguments:
            - "@repository.user"
            - "@router"